---
kind: pipeline
name: agilelabs.framework.docs
type: exec
node:
  runner_name: cn-build-02

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: build
    when:
      branch:
        - main
    environment:
      HUB_HOST: "hub.feinian.net"
      HUB_USERNAME: 
        from_secret: HUB_USERNAME
      HUB_PASSWORD: 
        from_secret: HUB_PASSWORD  
      KUBECONFIG: /root/.kube/config              
    commands:
      - export APP_NAME=agilelabs_docs
      - export IMAGE_VERSION=$(date +'%y%m%d_%H%M%S')
      - export BUILD_VERSION=$${APP_NAME}_$${IMAGE_VERSION}
      - echo "current version:" $BUILD_VERSION
      - docker run --rm -v `pwd`:/workdir --workdir /workdir -v /data/build_share/pnpm_store:/pnpm_store 
        hub.feinian.net/library/node:20-alpine /bin/sh -c "node --version && npm config set registry https://registry.npmmirror.com && npm i -g pnpm && pnpm install --store=/pnpm_store && pnpm run build"
      - echo $BUILD_VERSION > `pwd`/build/version.txt

      - docker login --username $$HUB_USERNAME --password $$HUB_PASSWORD $$HUB_HOST
      - docker build -t $HUB_HOST/agilelabs/$APP_NAME:$IMAGE_VERSION --file `pwd`/Dockerfile `pwd`/build
      - docker push $HUB_HOST/agilelabs/$APP_NAME:$IMAGE_VERSION
      - export DEPLOY_APP_NAME=agilelabs/$APP_NAME
      - echo "kubectl -n agilelabs set image deployment/agilelabs-docs agilelabs-docs=$HUB_HOST/$DEPLOY_APP_NAME:$IMAGE_VERSION"
      - kubectl -n wagilelabs001 set image deployment/agilelabs-docs agilelabs-docs=$HUB_HOST/$DEPLOY_APP_NAME:$IMAGE_VERSION